create sequence USER_DETAILS_SEQ
start with 1
increment by 1
minvalue 0
maxvalue 99999
nocycle;

create table USER_DETAILS( 
  ID INTEGER(5) NOT NULL,
  FIRST_NAME VARCHAR2(20) NOT NULL,
  LAST_NAME VARCHAR2(20) NOT NULL,
  EMAIL VARCHAR2(20) NOT NULL,
  MOBILE_NO INTEGER(20) NOT NULL ,
  WALLET_ID VARCHAR2(36) NOT NULL
);

commit;

create table WALLET_DETAILS( 
  WALLET_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  WALLET_NAME VARCHAR2(20) NOT NUL,
  AMOUNT INTEGER(10) NOT NULL,
  CREATED_BY VARCHAR2(20) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  STATUS VARCHAR2(10) NOT NULL
);

commit;



create table TXN_DETAILS( 
  TXN_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  WALLET_ID VARCHAR2(36) NOT NULL,
  USER_ID VARCHAR2(20) NOT NULL,
  TXN_TYPE VARCHAR2(10) NOT NULL,
  AMOUNT INTEGER(10) NOT NULL,
  TXN_TIME TIMESTAMP NOT NULL,
  FOREIGN KEY(WALLET_ID) REFERENCES WALLET_DETAILS(WALLET_ID),
  FOREIGN KEY(USER_ID) REFERENCES USER_DETAILS(USER_ID)
  
);