create sequence USER_DETAILS_SEQ
start with 1
increment by 1
minvalue 0
maxvalue 99999
nocycle; <!-- not used, since mysql doesnt have sequences... instead used the AUTO_INCREMENT feature-->

create table USER_DETAILS( 
  ID INTEGER(5) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(20) NOT NULL,
  MOBILE_NO INTEGER(20) NOT NULL,
  WALLET_ID VARCHAR(36) NOT NULL,
  PRIMARY KEY (ID)
)
AUTO_INCREMENT = 1;

create table WALLET_DETAILS( 
  WALLET_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  WALLET_NAME VARCHAR(20) NOT NULL,
  AMOUNT INTEGER(10) NOT NULL,
  CREATED_BY VARCHAR(20) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  STATUS VARCHAR(10) NOT NULL
);

commit;


create table TXN_DETAILS( 
  TXN_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  WALLET_ID VARCHAR(36) NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  TXN_TYPE VARCHAR(10) NOT NULL,
  AMOUNT INTEGER(10) NOT NULL,
  TXN_TIME TIMESTAMP NOT NULL,
  FOREIGN KEY(WALLET_ID) REFERENCES WALLET_DETAILS(WALLET_ID)
  );
commit;